openapi: 3.0.0
info:
  title: Chat App REST API Docs
  version: 1.0.0
  description: This is a simple CRUD API application made with Express and documented with Swagger
paths:
  /userInfo:
    get:
      summary: Gets all User Info
      description: Gets all Users and their corresponding details
      responses:
        "200":
          description: A JSON array of users and corresponding details
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    userId:
                      type: number
                      required: true
                      example: "12345"
                    email:
                      type: string
                      required: true
                      example: sample@gmail.com
                    username:
                      type: string
                      required: true
                      example: Mike Jones
                    bio:
                      type: string
                      required: true
                      example: I like to bike
        "500":
          description: Internal Server Error
  /user:
    post:
      summary: Create a new User
      description: Create a new User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  required: true
                  example: Mike123
                password:
                  type: string
                  required: true
                  example: password123
      responses:
        "201":
          description: Successfully created User
        "400":
          description: Invalid Request
        "500":
          description: Internal Server Error
    delete:
      summary: Delete a User
      description: Remove a User and their data from our records
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  required: true
                  example: 12345
      responses:
        "200":
          description: Successfully deleted User and Details
        "400":
          description: Invalid Request
        "500":
          description: Internal Server Error
